### ISSUE TITLE
[Front] Create login and register page

### ISSUE THREAD

**Issue by kconde2** [kconde2/vote-app#2]
- [ ] Create and integrate login page

- [ ] Create and integrate registration page

**Comment by dachic** [comment]
cette issue n'a pas lieu d'être puisque la #4 la repend....

**Comment by kconde2** [comment]
En effet, mais c'était pour faire un découplage du front et du back
Pendant que quelqu'un est entrain de faire le front l'autre fait le back

**Comment by dachic** [comment]
sur l'autre t'as mis api et front...
